### PR TITLE
Fix the scout termination issue

### LINKED ISSUE #180: [Bug] z_scout fails to terminate
### Describe the bug

https://github.com/eclipse-zenoh/zenoh-python/pull/173#issuecomment-2051170798

### To reproduce

1. Checkout the branch https://github.com/eclipse-zenoh/zenoh-python/tree/fix/uhlc
2. Run the example z_scout.py

### System info

Skip

### PR DESCRIPTION
**Pull request by YuanYuYuan**
Closes #180.

### CODE REVIEW

**Comment by YuanYuYuan** [comment]
Finally, we made it. We can supersede #173 with this PR as it has already included it. Once https://github.com/eclipse-zenoh/zenoh/pull/946 is merged, we can switch the upstream back to eclipse-zenoh.

**Comment by Mallets** [comment]
@wyfo can you please review?

**Comment by wyfo** [comment]
The solution here has not to be modifying zenoh code. The issue is a deadlock in `_Scout` drop, so we just need to update this operation on zenoh-python side, I will push a PR.

**Comment by YuanYuYuan** [comment]
Superseded by #188

**Pull request closed without merging**
